import { useEffect, useRef, useState } from 'react'
import { AlertCircle, CheckCircle, XCircle } from 'lucide-react'

import { useAuth } from '../context/AuthContext.jsx'
import api from '../utils/api.js'
import Card from '../components/layout/Card.jsx'

const emptyForm = {
  name: '',
  product_code: '',
  category: '',
  price: '',
  quantity: '',
  reorder_level: ''
}

const Inventory = () => {
  const { user } = useAuth()
  const [products, setProducts] = useState([])
  const [form, setForm] = useState(emptyForm)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [importing, setImporting] = useState(false)
  const [importFeedback, setImportFeedback] = useState(null)
  const fileInputRef = useRef(null)

  // Quantity update state
  const [selectedProductId, setSelectedProductId] = useState('')
  const [quantityToAdd, setQuantityToAdd] = useState('')
  const [priceToUpdate, setPriceToUpdate] = useState('')
  const [updating, setUpdating] = useState(false)
  const [productSearchTerm, setProductSearchTerm] = useState('')
  const [showDropdown, setShowDropdown] = useState(false)

  const canManage = user?.role === 'owner' || user?.role === 'manager'

  const loadProducts = async () => {
    setLoading(true)
    setError(null)
    try {
      const { data } = await api.get('/products/')
      setProducts(data)
    } catch (err) {
      setError(err?.response?.data?.detail || 'Failed to load products')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadProducts()
  }, [])

  const handleChange = (event) => {
    const { name, value } = event.target
    setForm((prev) => ({ ...prev, [name]: value }))
  }

  const handleSubmit = async (event) => {
    event.preventDefault()
    if (!canManage) return

    try {
      // Don't send product_code - it will be auto-generated by backend
      const { product_code, ...formData } = form
      await api.post('/products/', {
        ...formData,
        price: parseFloat(form.price),
        quantity: parseInt(form.quantity, 10),
        reorder_level: parseInt(form.reorder_level, 10)
      })
      setForm(emptyForm)
      setImportFeedback(null)
      loadProducts()
    } catch (err) {
      setError(err?.response?.data?.detail || 'Unable to create product')
    }
  }

  const handleQuantityUpdate = async (event) => {
    event.preventDefault()
    if (!canManage || !selectedProductId) return

    setUpdating(true)
    setError(null)

    try {
      const product = products.find(p => p.id === Number(selectedProductId))
      if (!product) {
        setError('Product not found')
        return
      }

      const updatePayload = {}
      
      // Update quantity if provided
      if (quantityToAdd) {
        const newQuantity = product.quantity + parseInt(quantityToAdd, 10)
        updatePayload.quantity = newQuantity
      }
      
      // Update price if provided
      if (priceToUpdate) {
        updatePayload.price = parseFloat(priceToUpdate)
      }

      if (Object.keys(updatePayload).length === 0) {
        setError('Please enter quantity to add or new price')
        setUpdating(false)
        return
      }

      await api.put(`/products/${selectedProductId}`, updatePayload)

      setSelectedProductId('')
      setQuantityToAdd('')
      setPriceToUpdate('')
      setProductSearchTerm('')
      setShowDropdown(false)
      setImportFeedback(null)
      loadProducts()
    } catch (err) {
      setError(err?.response?.data?.detail || 'Unable to update product')
    } finally {
      setUpdating(false)
    }
  }

  const filteredProductsForUpdate = products.filter((p) => {
    const term = productSearchTerm.toLowerCase().trim()
    if (!term) return false
    return (
      p.name.toLowerCase().includes(term) ||
      (p.product_code && p.product_code.toLowerCase().includes(term)) ||
      p.category.toLowerCase().includes(term)
    )
  })

  const handleExport = async () => {
    // Use the api helper so the Authorization header (JWT) is attached via interceptor
    try {
      const response = await api.get('/products/export', { responseType: 'blob' })
      const blob = new Blob([response.data], { type: 'text/csv;charset=utf-8;' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')

      // Try to derive filename from response headers, fallback to products.csv
      const disposition = response.headers['content-disposition'] || response.headers['Content-Disposition']
      let filename = 'products_export.csv'
      if (disposition) {
        const match = disposition.match(/filename="?([^";]+)"?/) // extracts filename
        if (match && match[1]) filename = match[1]
      }

      link.href = url
      link.setAttribute('download', filename)
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
    } catch (err) {
      // If not authenticated, provide helpful message
      if (err?.response?.status === 401) {
        setError('You must be logged in to export CSV. Please sign in and try again.')
      } else {
        setError(err?.response?.data?.detail || 'Failed to export CSV')
      }
    }
  }

  const handleDownloadSample = () => {
    const sampleData = [
      ['name', 'product_code', 'category', 'price', 'quantity', 'reorder_level'],
      ['Example Product 1', 'PROD001', 'Electronics', '150.00', '50', '10'],
      ['Example Product 2', 'PROD002', 'Furniture', '350.00', '20', '5'],
      ['Example Product 3', 'PROD003', 'Clothing', '45.00', '100', '15']
    ]
    
    const csvContent = sampleData.map(row => row.join(',')).join('\n')
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const link = document.createElement('a')
    const url = URL.createObjectURL(blob)
    
    link.setAttribute('href', url)
    link.setAttribute('download', 'product_import_sample.csv')
    link.style.visibility = 'hidden'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  const handleImportClick = () => {
    setImportFeedback(null)
    fileInputRef.current?.click()
  }

  const handleImport = async (event) => {
    const file = event.target.files?.[0]
    if (!file) return

    setImporting(true)
    setImportFeedback(null)
    setError(null)

    try {
      const formData = new FormData()
      formData.append('file', file)
      const { data } = await api.post('/products/import', formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      })

      const summaryParts = []
      if (data.created) summaryParts.push(`${data.created} created`)
      if (data.updated) summaryParts.push(`${data.updated} updated`)
      if (data.skipped) summaryParts.push(`${data.skipped} skipped`)

      setImportFeedback({
        type: 'success',
        message: summaryParts.length ? summaryParts.join(' - ') : 'CSV processed (no changes)',
        errors: data.errors || []
      })
      await loadProducts()
    } catch (err) {
      setImportFeedback({
        type: 'error',
        message: err?.response?.data?.detail || 'Import failed. Check your CSV headers and try again.',
        errors: []
      })
    } finally {
      setImporting(false)
      event.target.value = ''
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="font-heading text-2xl text-primary">Inventory</h2>
          <p className="text-sm text-slate-500">Manage product catalogue, stock levels, and bulk updates.</p>
        </div>
      </div>

      <Card
        title="Inventory shortcuts"
        description="Import or export products using CSV templates to update stock in bulk."
        actions={
          <div className="flex flex-col gap-2 sm:flex-row">
            <button
              type="button"
              onClick={handleDownloadSample}
              className="rounded-md border border-slate-200 bg-slate-50 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100"
            >
              Download Sample CSV
            </button>
            <button
              type="button"
              onClick={handleExport}
              className="rounded-md border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50"
            >
              Export CSV
            </button>
            {canManage ? (
              <button
                type="button"
                onClick={handleImportClick}
                disabled={importing}
                className="rounded-md border border-dashed border-primary px-4 py-2 text-sm font-medium text-primary disabled:cursor-not-allowed disabled:border-slate-200 disabled:text-slate-400"
              >
                {importing ? 'Importing…' : 'Import CSV'}
              </button>
            ) : null}
          </div>
        }
      >
        {canManage ? (
          <>
            <input
              ref={fileInputRef}
              type="file"
              accept=".csv,text/csv"
              onChange={handleImport}
              className="hidden"
            />
            {importFeedback ? (
              <div
                className={`rounded-lg border px-4 py-3 text-sm ${
                  importFeedback.type === 'success'
                    ? 'border-emerald-200 bg-emerald-50 text-emerald-700'
                    : 'border-red-200 bg-red-50 text-red-700'
                }`}
              >
                <div className="flex items-center justify-between gap-4">
                  <p>{importFeedback.message}</p>
                  <button
                    type="button"
                    onClick={() => setImportFeedback(null)}
                    className="text-xs font-semibold uppercase tracking-wide text-slate-500 hover:text-slate-700"
                  >
                    Dismiss
                  </button>
                </div>
                {importFeedback.errors?.length ? (
                  <ul className="mt-2 list-disc space-y-1 pl-5 text-xs">
                    {importFeedback.errors.slice(0, 5).map((msg, idx) => (
                      <li key={idx}>{msg}</li>
                    ))}
                    {importFeedback.errors.length > 5 ? <li>...more rows omitted</li> : null}
                  </ul>
                ) : null}
              </div>
            ) : (
              <p className="text-xs text-slate-400">
                Upload the sample template provided in <span className="font-medium text-slate-500">Resources</span> to
                update prices or quantities in bulk.
              </p>
            )}
          </>
        ) : (
          <p className="text-xs text-slate-400">
            Download the current inventory snapshot for quick reviews or offline analysis.
          </p>
        )}
      </Card>

      {error ? <p className="text-sm text-red-600">{error}</p> : null}

      {canManage ? (
        <div className="grid gap-6 lg:grid-cols-2">
          <Card
            title="Update stock quantity & price"
            description="Select an existing product to update its stock level or pricing."
          >
            <form onSubmit={handleQuantityUpdate} className="space-y-4">
              <div className="relative">
                <input
                  type="text"
                  placeholder="Search products by name or code..."
                  value={productSearchTerm}
                  onChange={(e) => {
                    setProductSearchTerm(e.target.value)
                    setShowDropdown(true)
                  }}
                  onFocus={() => setShowDropdown(true)}
                  className="w-full rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-primary focus:outline-none"
                />
                {showDropdown && productSearchTerm && (
                  <div className="absolute z-10 mt-1 w-full max-h-60 overflow-auto rounded-md border border-slate-200 bg-white shadow-lg">
                    {filteredProductsForUpdate.length > 0 ? (
                      filteredProductsForUpdate.map((p) => (
                        <div
                          key={p.id}
                          onClick={() => {
                            setSelectedProductId(String(p.id))
                            setProductSearchTerm(`${p.name} ${p.product_code ? `(${p.product_code})` : ''}`)
                            setShowDropdown(false)
                            // Pre-fill current price for easy editing
                            setPriceToUpdate(String(p.price))
                          }}
                          className={`px-3 py-2 text-sm cursor-pointer hover:bg-slate-50 ${
                            Number(selectedProductId) === p.id ? 'bg-primary/10 border-l-4 border-primary' : ''
                          }`}
                        >
                          <div className="font-medium">{p.name}</div>
                          <div className="text-xs text-slate-500 flex items-center gap-1">
                            <span>{p.product_code ? `Code: ${p.product_code} | ` : ''}Stock: {p.quantity} | Price: ZMW {p.price.toFixed(2)}</span>
                            {p.quantity === 0 ? (
                              <span className="flex items-center gap-1 text-red-600">
                                <XCircle className="w-3 h-3" /> OUT OF STOCK
                              </span>
                            ) : p.quantity <= p.reorder_level ? (
                              <span className="flex items-center gap-1 text-orange-600">
                                <AlertCircle className="w-3 h-3" /> Low
                              </span>
                            ) : (
                              <CheckCircle className="w-3 h-3 text-green-600" />
                            )}
                          </div>
                        </div>
                      ))
                    ) : (
                      <div className="px-3 py-2 text-sm text-slate-400">No products found</div>
                    )}
                  </div>
                )}
              </div>
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-medium text-slate-600 mb-1">Quantity to Add</label>
                  <input
                    type="number"
                    min="1"
                    placeholder="e.g., 10"
                    value={quantityToAdd}
                    onChange={(e) => setQuantityToAdd(e.target.value)}
                    className="w-full rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-primary focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-slate-600 mb-1">Update Price (ZMW)</label>
                  <input
                    type="number"
                    step="0.01"
                    min="0"
                    placeholder="e.g., 25.00"
                    value={priceToUpdate}
                    onChange={(e) => setPriceToUpdate(e.target.value)}
                    className="w-full rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-primary focus:outline-none"
                  />
                </div>
                <button
                  type="submit"
                  disabled={updating || !selectedProductId || (!quantityToAdd && !priceToUpdate)}
                  className="w-full rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white hover:bg-primary/90 disabled:bg-slate-300 disabled:cursor-not-allowed"
                >
                  {updating ? 'Updating...' : 'Update Product'}
                </button>
              </div>
            </form>
          </Card>

          <Card
            title="Add product"
            description="Capture individual items to keep stock levels accurate."
          >
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid gap-4 md:grid-cols-2">
                <input
                  required
                  type="text"
                  name="name"
                  placeholder="Product name"
                  value={form.name}
                  onChange={handleChange}
                  className="rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-primary focus:outline-none"
                />
                <input
                  required
                  type="text"
                  name="category"
                  placeholder="Category"
                  value={form.category}
                  onChange={handleChange}
                  className="rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-primary focus:outline-none"
                />
              </div>
              <div className="rounded-md border border-slate-100 bg-slate-50 px-3 py-2 text-sm text-slate-500 flex items-center">
                Product Code- Auto generated
              </div>
              <div className="grid gap-4 md:grid-cols-3">
                <input
                  required
                  type="number"
                  step="0.01"
                  name="price"
                  placeholder="Price"
                  value={form.price}
                  onChange={handleChange}
                  className="rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-primary focus:outline-none"
                />
                <input
                  required
                  type="number"
                  name="quantity"
                  placeholder="Qty"
                  value={form.quantity}
                  onChange={handleChange}
                  className="rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-primary focus:outline-none"
                />
                <input
                  required
                  type="number"
                  name="reorder_level"
                  placeholder="Reorder level"
                  value={form.reorder_level}
                  onChange={handleChange}
                  className="rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-primary focus:outline-none"
                />
              </div>
              <button
                type="submit"
                className="w-full rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white hover:bg-primary/90"
              >
                Add product
              </button>
            </form>
          </Card>
        </div>
      ) : null}

      <Card
        title="Product catalogue"
        description="A live list of all items with current pricing and stock levels."
      >
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-slate-200 text-sm">
            <thead className="bg-slate-50">
              <tr className="text-left text-xs font-semibold uppercase tracking-wide text-slate-600">
                <th className="px-4 py-3">Name</th>
                <th className="px-4 py-3">Product Code</th>
                <th className="px-4 py-3">Category</th>
                <th className="px-4 py-3">Price</th>
                <th className="px-4 py-3">Quantity</th>
                <th className="px-4 py-3">Reorder level</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading ? (
                <tr>
                  <td colSpan="6" className="px-4 py-6 text-center text-slate-500">
                    Loading products...
                  </td>
                </tr>
              ) : products.length ? (
                products.map((product) => (
                  <tr key={product.id} className={`hover:bg-slate-50 ${product.quantity === 0 ? 'bg-red-50' : ''}`}>
                    <td className="px-4 py-3 font-medium text-slate-700">{product.name}</td>
                    <td className="px-4 py-3 text-slate-500">{product.product_code || '-'}</td>
                    <td className="px-4 py-3">{product.category}</td>
                    <td className="px-4 py-3">ZMW {product.price.toFixed(2)}</td>
                    <td className="px-4 py-3">
                      <span className={`flex items-center gap-1 ${product.quantity === 0 ? 'text-red-600 font-semibold' : ''}`}>
                        {product.quantity}
                        {product.quantity === 0 ? (
                          <span className="flex items-center gap-1">
                            <XCircle className="w-4 h-4" /> OUT OF STOCK
                          </span>
                        ) : product.quantity <= product.reorder_level ? (
                          <AlertCircle className="w-4 h-4 text-orange-600" />
                        ) : null}
                      </span>
                    </td>
                    <td className="px-4 py-3">{product.reorder_level}</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="6" className="px-4 py-6 text-center text-slate-500">
                    No products yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>

      {canManage ? (
        <Card
          title="CSV tips"
          description="Keep these guidelines in mind when preparing your import files."
        >
          <ul className="space-y-2 text-sm text-slate-500">
            <li>
              - Use headers:{' '}
              <code className="rounded bg-slate-100 px-1">name</code>,{' '}
              <code className="rounded bg-slate-100 px-1">category</code>,{' '}
              <code className="rounded bg-slate-100 px-1">price</code>,{' '}
              <code className="rounded bg-slate-100 px-1">quantity</code>,{' '}
              <code className="rounded bg-slate-100 px-1">reorder_level</code>
            </li>
            <li>
              - Include <code className="rounded bg-slate-100 px-1">id</code> or{' '}
              <code className="rounded bg-slate-100 px-1">name</code> to update existing products; omit to add new ones.
            </li>
            <li>
              - Prices and quantities should be positive numbers. Leave fields blank to keep current values.
            </li>
          </ul>
        </Card>
      ) : null}
    </div>
  )
}

export default Inventory
